# fly.toml app configuration file generated for social-circle on 2025-08-11T21:42:13-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'social-circle'
primary_region = 'sjc'
kill_signal = 'SIGTERM'

[build]

[deploy]
  release_command = '/app/bin/migrate'

[env]
  PHX_HOST = 'social.qingbo.us'
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 1000
    soft_limit = 1000

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
  guest_path = '/app/lib/social_circle_web-0.1.0/priv/static'
  url_prefix = '/static/'

# Custom domain configuration
# After deploying, run: flyctl certs add social.qingbo.us
# Then configure your DNS to point social.qingbo.us to your Fly.io app
